name: Deploy

on: [push]

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Generate
        run: |
          node script/test.js

      - name: Commit
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}"
          git config user.email "lockdown-bot@non-existing.com"
          git config user.name "lockdown-bot"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only

          git add foo.txt

          git commit -m "Update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: test-cron-job-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
