name: Deploy

on: [push]

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Update data
        run: |
          node script/test.js

      - name: Commit changes
        run: |
          git config user.email "lockdown-bot@non-existing.com"
          git config user.name "lockdown-bot"

          git add foo.txt

          git commit -m "Update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: test-cron-job-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
